Update ios platform

diff --git a/app/platforms/ios/cordova/lib/list-emulator-images b/app/platforms/ios/cordova/lib/list-emulator-images
--- a/app/platforms/ios/cordova/lib/list-emulator-images
+++ b/app/platforms/ios/cordova/lib/list-emulator-images
@@ -16,25 +16,24 @@
 #  KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
-#
-# Valid values for "--target" (case insensitive):
-#     "iPhone Retina (3.5-inch)" (default)
-#     "iPhone Retina (4-inch)"
-#     "iPhone"
-#     "iPad"
-#     "iPad Retina"
 
 set -e
 
-echo \""iPhone (Retina 3.5-inch)"\"
-echo \""iPhone (Retina 4-inch)"\"
+IOS_SIM_MIN_VERSION="3.0"
+IOS_SIM_LOCATION=$(which ios-sim)
+if [ $? != 0 ]; then
+    echo -e "\033[31mError: ios-sim was not found. Please download, build and install version $IOS_SIM_MIN_VERSION or greater from https://github.com/phonegap/ios-sim into your path. Or 'npm install -g ios-sim' using node.js: http://nodejs.org/\033[m" 1>&2; 
+	exit 1;
+fi
 
-# this assumes Xcode 5 minimum not supported by ios-sim yet
-# echo \""iPhone (Retina 4-inch 64-bit)"\"
+IOS_SIM_VERSION=$(ios-sim --version)
 
-echo \""iPhone"\"
-echo \""iPad"\"
-echo \""iPad (Retina)"\"
+if [[ "$IOS_SIM_VERSION" < "$IOS_SIM_MIN_VERSION" ]]; then
+	echo "Cordova needs ios-sim version $IOS_SIM_MIN_VERSION or greater, you have version $IOS_SIM_VERSION." 1>&2;
+	exit 1
+fi
+
+ios-sim showdevicetypes 2>&1 | sed "s/com.apple.CoreSimulator.SimDeviceType.//g" | awk -F',' '{print $1}'
 
 
 
